server:
  port: 9999
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fengye0911/gogou-config.git
  application:
    name: GOGOU-CONFIG

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
management:
  endpoint:
    web:
      expose: "*"
